[workspace]
members = ["newtype-tools", "newtype-tools-derive"]
resolver = "2"

[workspace.package]
authors = ["Andriy Berestovskyy <berestovskyy@gmail.com>"]
categories = [
    "algorithms",
    "data-structures",
    "development-tools",
    "development-tools::procedural-macro-helpers",
    "rust-patterns",
]
description = "Ergonomic utilities for the Rust newtype idiom."
edition = "2024"
homepage = "https://github.com/berestovskyy/newtype-tools/releases"
keywords = ["conversion", "derive", "idiom", "iterator", "newtype"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/berestovskyy/newtype-tools"
rust-version = "1.86.0"
version = "1.0.15"

[workspace.dependencies]
newtype-tools-derive = { version = "1.0.15", path = "newtype-tools-derive" }
proc-macro2 = "1.0.106"
quote = "1.0.45"
rstest = "0.26.1"
rustversion = "1.0.22"
serde = { version = "1.0.228", features = ["derive"] }
syn = { version = "3.0.3", features = ["full"] }
trybuild = "1.0.116"
