name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  config:
    name: Configuring Rust Versions
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      msrv: "1.86.0" # Also update `rust-version` in root `Cargo.toml` and `Makefile`.
      stable: stable
      nightly: nightly
    steps:
      - run: echo "Configuring Rust versions..."

  ci:
    needs: config
    name: Rust ${{ matrix.toolchain }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - ${{ needs.config.outputs.msrv }}
          - ${{ needs.config.outputs.stable }}
          - ${{ needs.config.outputs.nightly }}
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        id: rust-toolchain
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: OS:${{runner.os}}
            Rust:${{matrix.toolchain}}-fmt-clippy-${{steps.rust-toolchain.outputs.cachekey}}
            Lock:${{hashFiles('**/Cargo.lock')}}

      - name: Clippy (Default Features)
        if: matrix.toolchain == needs.config.outputs.stable
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Build (Default Features)
        run: cargo build
      - name: Test (Default Features)
        run: cargo test

      - name: Build (Minimal Features)
        run: cargo build --no-default-features
      - name: Test (Minimal Features)
        run: cargo test --no-default-features

      - name: Build (Unstable Features)
        if: matrix.toolchain == needs.config.outputs.nightly
        run: cargo build --all-features
      - name: Test (Unstable Features)
        if: matrix.toolchain == needs.config.outputs.nightly
        run: cargo test --all-features

      - name: Formatting
        if: matrix.toolchain == needs.config.outputs.nightly
        run: cargo fmt --all -- --check --config
          reorder_impl_items=true,error_on_unformatted=true,error_on_line_overflow=true

  # If this fails, consider changing your text or adding something to `.typos.toml`.
  typos:
    name: Check typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: crate-ci/typos@v1.45.1

  # Make sure the library builds with all dependencies downgraded to their
  # oldest versions allowed by the semver spec. This ensures we have not
  # under-specified any dependency.
  minimal-versions:
    needs: config
    name: Check Minimal Version
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@master
        id: msrv-toolchain
        with:
          toolchain: ${{ needs.config.outputs.msrv }}
      - uses: dtolnay/rust-toolchain@master
        id: nightly-toolchain
        with:
          toolchain: ${{ needs.config.outputs.msrv }}
      - uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: OS:${{runner.os}}
            Rust:${{needs.config.outputs.msrv}}-${{steps.msrv-toolchain.outputs.cachekey}}
            Rust:${{needs.config.outputs.nightly}}-${{steps.nightly-toolchain.outputs.cachekey}}
            Lock:${{hashFiles('**/Cargo.lock')}}

      - name: Downgrade dependencies to minimal versions
        run: cargo "+${{ needs.config.outputs.nightly }}" update -Z minimal-versions

      - name: Compile with minimal versions
        run: cargo "+${{ needs.config.outputs.msrv }}" build --all-targets --locked
